// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbngoljbxnmbskkmruiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxibmdvbGpieG5tYnNra21ydWl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTU5MjUsImV4cCI6MjA1OTY3MTkyNX0.Ev3tC-mfOsHFGHiN7y2mZ8xpEq9WThM6hfzPlCcryg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);